### ISSUE TITLE
Initial implementation of the functionality to create a project on the client side and send to the API

### ISSUE THREAD

**Issue by viniciusfk9** [viniciusfk9/pifano#12]
### TODO:
- [ ] Client-side:
  - [X] Initialize a Project object
  - [X] Push the Project object to the API
  - [ ] Unit tests
- [ ] Server-side:
  - [X] Endpoint that receives a Project object and saves to the database
  - [ ] Unit tests
